Changed all instances of event_name to hackathon_name and updated jin…
ieeeuoft/hackathon-template pull request #208
Opened 2020-10-22 23:20 UTC by siddvader333

- Resolves #207 
- Changed all instances of event_name to hackathon_name
- moved email templates from registration to review
- updated jinja settings and removed context setting of "hackathon_name"

## Unit Tests Created
N/A no new unit tests created.

## Steps to QA
- can view updated views to verify consistency and functionality

2020-10-22 23:32 UTC, albogdan submitted a review, later dismissed

2020-10-22 23:45 UTC, grahamhoyes requested changes

2020-10-22 23:45 UTC, grahamhoyes commented on hackathon_site/registration/views.py
>      def get_email_context(self, activation_key):
This entire method can be deleted

2020-10-23 03:08 UTC, albogdan approved these changes

2020-10-23 03:11 UTC, grahamhoyes approved these changes
Chancing a review from my phone here, a grep search earlier indicated that all was in order so LGTM

2020-10-23 03:18 UTC, merged