Remove hardcoded dashboard dates
ieeeuoft/hackathon-template pull request #262
Opened 2021-05-05 21:17 UTC by albogdan

## Overview

- Resolves #211
- <Description of all changes made and features implemented>

## Unit Tests Created

- <Briefly describe unit tests that were created>

## Steps to QA

- <Steps for a reviewer to QA your work>

2021-05-05 22:13 UTC, lisa-sa-li requested changes

2021-05-05 22:13 UTC, lisa-sa-li commented on hackathon_site/event/jinja2/event/dashboard_base.html
> +                <p class="faqAnswer">The rank on the waitlist is first-come first serve, meaning the sooner you arrive at the event on {{ event_start_date.strftime("%A") }}, the higher your placement
instead of `{{ event_start_date.strftime("%I%p") }}` it should use `WAITLISTED_ACCEPTANCE_START_TIME`

2021-05-06 02:58 UTC, grahamhoyes commented on hackathon_site/event/jinja2/event/dashboard_base.html
> +                <p class="faqAnswer">The rank on the waitlist is first-come first serve, meaning the sooner you arrive at the event on {{ waitlisted_acceptance_start_time.strftime("%A") }}, the highe
Space before %p

2021-05-06 02:58 UTC, grahamhoyes commented on hackathon_site/event/views.py
> +import pytz
Minor, out this after Django imports and whatever else for alphabetical order

2021-05-06 02:58 UTC, grahamhoyes commented on hackathon_site/event/views.py
> +            rsvp_timezone = pytz.timezone(str(settings.TZ_INFO))
This is the same as settings.TZ_INFO no?

2021-05-06 14:48 UTC, grahamhoyes approved these changes

2021-05-07 03:18 UTC, lisa-sa-li approved these changes

2021-05-07 04:14 UTC, merged