IEEE 149: POST: /hardware/orders/returns/ - return items
ieeeuoft/hackathon-template pull request #417
Opened 2022-07-11 02:50 UTC by Mustaballer

## Overview

- Resolves #IEEE-149
- request body =
```
{
  "hardware": [
    {
      "id": 0,
      "quantity": 0,
      "part_returned_health": [Healthy, Heavily Used, Broken, Lost]
    }
  ],
  "order": <order id> ,
}
```
- validate hardware exists in inventory
- update order item part_returned_health 

## Unit Tests Created

- in progress

## Steps to QA

- check endpoint on swagger

## Questions/Issues
- [ ] I was able to replicate the request on swagger, is there anything I need to change?
- [ ] To validate if hardware exists in the inventory how would I update the view to check?
- [ ] I copied code from this serializer, OrderCreateSerializer, what should I keep or remove
- [ ] We update the part_returned_health but what would the response look like? I imagine that would be handled in the view
- [ ] Is there any issues you see rn with the code, and some resources I should look more into to better understand the ticket? 
- [ ] Suggestions to tackle this ticket?

2022-08-03 16:04 UTC, YuYing-Liang requested changes
Nice start Mustafa!

2022-08-03 16:04 UTC, YuYing-Liang commented on hackathon_site/hardware/serializers.py
> +                "Hardware array size must be greater or equal to one."
This is not very helpful to the user, what if they don't know what an array is? 
A better error message could be "No hardware specified in return request"

2022-08-03 16:04 UTC, YuYing-Liang commented on hackathon_site/hardware/serializers.py
> +                        "message": "Requested quantity was {} higher than available. {} was returned ".format(
code suggestion:
Instead of using .format() you can use the cool new python 3.6+ way of formatting strings like this (I changed up the first sentence bc of grammar)
```
f"Requested quantity of { hardware_item["quantity"] - len(order_items_with_hardware) } was higher than available. { max_available_quantity } was returned."
```
Also be careful of grammatical errors e.g. "1 was returned" vs. "2 **were** returned"

2022-08-03 16:04 UTC, YuYing-Liang commented on hackathon_site/hardware/serializers.py
> +                        "message": "There are 0 order items for this hardware. No hardware items were returned",
error message suggestion:
"There are no checked out items for this hardware, all have already been returned."

2022-08-03 16:04 UTC, YuYing-Liang commented on hackathon_site/hardware/serializers.py
> +                for status in hardware_item["HEALTH_CHOICES"]:
instead you can use this condition in python to eliminate the for loop:
```
if hardware_item["part_returned_health"] in HardwareItemReturnSerializer.HEALTH_CHOICES:
    < add error to array >
    continue
```
By placing the `continue` keyword in this if statement means you don't need the else block, it just makes your code look cleaner.

2022-08-03 16:04 UTC, YuYing-Liang commented on hackathon_site/hardware/serializers.py
> +    errors = OrderItemReturnSerializer(many=True, required=True)
Why does the error property have this serializer?

2022-08-03 16:04 UTC, YuYing-Liang commented on hackathon_site/hardware/serializers.py
> +
General comment here:
I realized there could be multiple errors per hardware item and a better way to group these errors is by hardware id instead of a flat array, could you change the error structure to be:
```
errors: {
    <hardware id>: [ <array of strings (error messages)>],
}
```

2022-08-04 06:21 UTC, Mustaballer commented on hackathon_site/hardware/serializers.py
> +    errors = OrderItemReturnSerializer(many=True, required=True)
Yeah I realized I should make a custome serializer. I mimicked OrderCreateResponseErrorSerializer
![image](https://user-images.githubusercontent.com/43456930/182777156-1e3c61ff-0c20-4519-9e16-cd271736b499.png)

2022-08-04 07:54 UTC, Mustaballer commented on hackathon_site/hardware/serializers.py
> +
I haven't implemented the error structure yet but when I try to test hardware with an incorrect response type on swagger I get this error
`{'required': 'This field is required.', 'null': 'This field may not be null.', 'invalid': 'Invalid data. Expected a dictionary, but got {datatype}.'}
Internal Server Error: /api/hardware/orders/returns/`

2022-08-04 08:25 UTC, Mustaballer commented on hackathon_site/hardware/serializers.py
> +
@YuYing-Liang I also noticed, that there isn't a returned status for the order which is why the order table still exists in the pending order section. Is that something I need to handle

![image](https://user-images.githubusercontent.com/43456930/182800101-3e820654-cdba-44a4-b013-66c56f28fc49.png)

2022-09-20 01:18 UTC, YuYing-Liang approved these changes, later dismissed

2022-09-20 01:22 UTC, Mustaballer commented on hackathon_site/dashboard/frontend/src/components/general/OrderTables/OrderTables.tsx
> +    console.log(orders);
remove log comment and everything should be good

2022-09-20 01:31 UTC, YuYing-Liang approved these changes

2022-09-20 01:35 UTC, merged