added searching and loading more teams features with tests
ieeeuoft/hackathon-template pull request #450
Opened 2022-12-23 18:54 UTC by YuYing-Liang

## Overview

- Copied over searching and loading more teams from newhacks repo

## Unit Tests Created

- made unit tests for searching teams, loading more teams and the teams search bar

## Steps to QA

- test searching teams, clearing search and loading more teams works properly on the hss admin side

2022-12-23 21:01 UTC, Leo6Leo requested changes
As commented above. The basic manual functionality test has passed.

2022-12-23 21:01 UTC, Leo6Leo commented on hackathon_site/dashboard/frontend/src/pages/Teams/Teams.test.tsx
> +    it("Loads more teams", async () => {
We could have one more test: if the number of teams is within the limit or all teams have been loaded, the load more button should be displayed

2022-12-23 21:01 UTC, Leo6Leo commented on hackathon_site/dashboard/frontend/src/components/team/TeamSearchBar/TeamSearchBar.test.tsx
> +
hitting "Enter" on the keyboard also work

2022-12-23 21:01 UTC, Leo6Leo commented on hackathon_site/dashboard/frontend/src/pages/Teams/Teams.tsx
>      const teamsList = useSelector(teamAdminSelectors.selectAll);
switch this with line 26, so that we put all `useSelector` together

2023-01-02 20:15 UTC, YuYing-Liang commented on hackathon_site/dashboard/frontend/src/pages/Teams/Teams.test.tsx
> +    it("Loads more teams", async () => {
Correct me if I'm wrong but I think that's what's tested in the following test (line 186)

2023-01-02 20:20 UTC, YuYing-Liang commented on hackathon_site/dashboard/frontend/src/components/team/TeamSearchBar/TeamSearchBar.test.tsx
> +
done

2023-01-02 20:20 UTC, YuYing-Liang commented on hackathon_site/dashboard/frontend/src/pages/Teams/Teams.tsx
>      const teamsList = useSelector(teamAdminSelectors.selectAll);
done

2023-01-08 07:17 UTC, Leo6Leo approved these changes, later dismissed
Looks good to me, great work Yuyingg!!!

2023-01-11 01:58 UTC, Mustaballer approved these changes

2023-01-11 02:01 UTC, merged