Ieee 242 update result count on order page
ieeeuoft/hackathon-template pull request #462
Opened 2023-01-07 21:32 UTC by danielqiuu

## Overview

- Resolves #<number>
- <Description of all changes made and features implemented>

## Unit Tests Created

- <Briefly describe unit tests that were created>

## Steps to QA

- <Steps for a reviewer to QA your work>

2023-02-13 21:48 UTC, Leo6Leo requested changes
Great work on this Redux ticket Daniel! Please refer to my comments above.

2023-02-13 21:48 UTC, Leo6Leo commented on hackathon_site/dashboard/frontend/src/components/orders/OrdersCount/OrdersCount.test.tsx
> +import OrdersCount from "./OrdersCount";
Put all third-party imports in a block, and put all our self-made imports into a block. What I mean self-made is the component/selectors we have created by ourselves, it is not any third-party library.

2023-02-13 21:48 UTC, Leo6Leo commented on hackathon_site/dashboard/frontend/src/components/orders/OrdersCount/OrdersCount.test.tsx
> +                {" "}
remove this will cause the test failing or no?

2023-02-13 21:48 UTC, Leo6Leo commented on hackathon_site/dashboard/frontend/src/components/orders/OrdersCount/OrdersCount.tsx
> +import { useSelector } from "react-redux";
same comment as above. 
Put all third-party imports in a block, and put all our self-made imports into a block. What I mean self-made is the component/selectors we have created by ourselves, it is not any third-party library.

2023-02-13 21:48 UTC, Leo6Leo commented on hackathon_site/dashboard/frontend/src/slices/order/adminOrderSlice.test.ts
> +import orders from "../../pages/Orders/Orders";
Put all third-party imports in a block, and put all our self-made imports into a block. What I mean self-made is the component/selectors we have created by ourselves, it is not any third-party library.

2023-02-16 03:49 UTC, danielqiuu commented on hackathon_site/dashboard/frontend/src/components/orders/OrdersCount/OrdersCount.test.tsx
> +                {" "}
Yes, this was the fix for the test

2023-02-17 03:50 UTC, Leo6Leo approved these changes
Looks good to me, great work Daniel!

2023-04-01 19:43 UTC, merged