Ieee 245 get review status by username
ieeeuoft/hackathon-template pull request #486
Opened 2023-05-28 23:29 UTC by liu-samuel

## Overview

- Resolves IEEE-245
- Added a new endpoint to get a user's review status based on username

## Unit Tests Created

- User Serializer Unit Tests in tests.py
- User Review Status Unit Tests in test_api.py

## Steps to QA

- N/A

2023-06-03 19:04 UTC, LunarFang416 submitted a review, later dismissed
LGTM

2023-06-03 20:04 UTC, lukecheseldine requested changes
great work Sam! this is almost ready, I'd just like you to add two more test cases.
1. the api is hit with an email that doesn't exist (return 400)
2. the api is hit without being logged in (return 401)
in general, we should try to write tests for all possible return codes. write these up and should be good to go!

2023-06-03 20:04 UTC, lukecheseldine commented on hackathon_site/event/api_views.py
> +    View to handle review status status of a user with a certain username
```suggestion
    View to handle review status of a user with a certain username
```

2023-06-03 20:27 UTC, liu-samuel commented on hackathon_site/event/api_views.py
> +    View to handle review status status of a user with a certain username
Changes are pushed

2023-06-03 20:46 UTC, lukecheseldine approved these changes
looks good, thanks for making those changes :)

2023-06-04 00:33 UTC, LunarFang416 approved these changes
👍👍

2023-06-04 22:53 UTC, merged