IEEE 215 *new* checked out order card
ieeeuoft/hackathon-template pull request #487
Opened 2023-05-29 04:38 UTC by natapokie

## Overview

- Resolves 215 Create Checked Out/Picked Up Order Card
- New order card called `OrderPending`
  - clickable order card that evokes an alert event with the order ID displayed
  - adding picked up and view buttons
  - once picked up is clicked, button is diabled along with the checkbox
- Note: changes from another member are attached to this branch

## Unit Tests Created

- front end test to make sure details are displayed on card

## Steps to QA

- use the mockPendingOrders from mock data and call the OrderPending component in the Orders page instead of allOrders
- clicking on the card will evoke the alert
- clicking on picked up disables itself and the checkbox

![image](https://github.com/ieeeuoft/hackathon-template/assets/86009011/2327d7c4-b86d-4bd8-9081-ccf918b037d9)

2023-06-01 04:46 UTC, Mustaballer requested changes
Natalie, great job! I'm amazed by the quality of your code especially since its your first PR in the codebase. I left some minor comments below, next steps would be to use real data. Before we delve into that, I do want to ask you some questions regarding the designs.

1. Do you think its immediately obvious the difference between `Picked Up` and `Ready for Pickup` orders? If not you can look into modifying the design to be more obvious.
2. Right now we have custom order models for `Picked Up` and `Ready for Pickup`, are you interested in desigining new Order cards for other statuses.(We could also make updates to the current Order Cards) 

Overall we're pretty flexible with the design, so do let me know what you think of the OrderCards and how we can make them both simple and easy to undestand.

2023-06-01 04:46 UTC, Mustaballer commented on hackathon_site/dashboard/frontend/src/components/orders/OrderCard/OrderPending.test.tsx
> +            // { title: "Received IDs", value: receivedIDs },
Should remove if not being used

2023-06-01 04:46 UTC, Mustaballer commented on hackathon_site/dashboard/frontend/src/components/orders/OrderCard/OrderPending.tsx
> +                    console.log(values);
Please remove logging in the final version :)

2023-06-01 04:46 UTC, Mustaballer commented on hackathon_site/dashboard/frontend/src/components/orders/OrderCard/OrderPending.tsx
> +                                // console.log("click picked up");
remove comment

2023-06-01 04:46 UTC, Mustaballer commented on hackathon_site/dashboard/frontend/src/components/orders/OrderCard/OrderPending.tsx
> +                            // type="submit"
remove comment

2023-06-01 04:46 UTC, Mustaballer commented on hackathon_site/dashboard/frontend/src/components/orders/OrderCard/OrderPending.tsx
> +                                console.log("click view");
pls remove log

2023-06-01 04:46 UTC, Mustaballer commented on hackathon_site/dashboard/frontend/src/components/orders/OrderCard/OrderPending.tsx
> +    team: string;
This should be team code and should still be a string

2023-06-02 01:51 UTC, natapokie commented
> Natalie, great job! I'm amazed by the quality of your code especially since its your first PR in the codebase. I left some minor comments below, next steps would be to use real data. Before we delve into that, I do want to ask you some questions regarding the designs.
> 
> 1. Do you think its immediately obvious the difference between `Picked Up` and `Ready for Pickup` orders? If not you can look into modifying the design to be more obvious.
> 2. Right now we have custom order models for `Picked Up` and `Ready for Pickup`, are you interested in desigining new Order cards for other statuses.(We could also make updates to the current Order Cards)
> 
> Overall we're pretty flexible with the design, so do let me know what you think of the OrderCards and how we can make them both simple and easy to undestand.

Thank you! But I only made adjustments to the code that was written previously haha, to answer your questions...

1. To be completely honest, as someone who had no prior experience with the HSS I didn't immediately figure out which design was the `Picked Up` and `Ready for Pickup` orders. One thing that I would like to propose is actually using a table instead of an order card? To me the orders system feels really similar to Shopify where there are different statuses for items for example...
    - "Unfulfilled" means the order is not ready
    - "Ready for Pickup" 
    - "Fulfiled" when the order has been picked up

  Kinda like this...!
  ![image](https://github.com/ieeeuoft/hackathon-template/assets/86009011/65a82da5-73cc-4ca3-9f08-fadd3ebf8693)

I think the table would allow us to easily incorporate the other "states" like pending and even cancelled orders and this way we wouldn't have to make too many components that are really similar...! And another idea, we can probably have a state for 
"Preparing", I remember when I was helping out last year, we ended up doing an order that someone else was already preparing.
Let me know what you think about that... and I can mock up a separate design on Figma ;)

And also for 2. yes, I can make more order cards as well if we decide to go that route!

2023-06-02 19:54 UTC, Mustaballer commented
Hey Natalie, I really like the idea of using a table for handling orders! I think it'd be pretty straightforward in figuring out what orders need to be done, and help us manage them more effectively. I think it'd be great if you could mock up a design on Figma :)
Regarding the preparing status, I also think that's a good idea, but we should be considering how to make it work in real time since we have to refresh the HSS since its not in real time.

2023-06-04 23:15 UTC, closed without merging