IEEE 253 fixing order modal cancel bug
ieeeuoft/hackathon-template pull request #491
Opened 2023-05-30 20:57 UTC by carmen-chau

## Overview

Description: This PR (for Jira ticket IEEE-253) contains preliminary fixes to the order modal cancel bug. This fix enables users (on the participant time) to correctly cancel desired orders directly from the cancel order pop-up modal 

Speculation as to why the bug occurred: The reason why orders were being canceled in chronological order is that in the submitModal() method, the orderID being retrieved is always the most recent orderID (which as a result, would cancel the most recent order, not the order in which the participant originally wanted). Uncertain as to why this is the case, though I speculate it might be due to the fact that the modal submission process occurs only after all buttons have been created (aka "mapped" to each order in OrderInTable. Will need to further investigate to confirm or disprove this. 

Summary of changes: Created a new variable called orderId that stores the desired canceled order's id based on the "Cancel order" button press. The state of this variable is updated each time the button is being pressed and should work even when multiple orders are pending. 

## Unit Tests Created

- Did not create nor modify any unit tests

## Steps to QA

- Would appreciate suggestions to improve or rewrite current solution based on best practices. Would also appreciate testing to see whether bug is fully resolved with this solution and/or other ideas as to why the bug originated in the first place.

2023-06-03 04:39 UTC, Mustaballer requested changes
It seems like the issue arises due to event bubbling, causing the most recent orderID to always be retrieved. event.stopPropagation() could be a potential solution as it would prevent the onClick event from propagating to outer elements or handlers. Could you look into using that instead of the state variables?

2023-06-04 22:12 UTC, Mustaballer requested changes
Could you try using event.stopPropagation() in ItemTables.tsx or whichever file you call the PupupModal when the cancel order button is clicked?

2023-06-10 18:17 UTC, Mustaballer commented
Hey @carmen-chau if the `event.propogation`, doesn't work we can try your initial method that does delete order items properly.

2023-06-11 01:50 UTC, danielqiuu approved these changes, later dismissed

2023-06-12 18:46 UTC, lukecheseldine submitted a review, later dismissed
LGTM, great job Carmen!

2023-06-13 01:35 UTC, Mustaballer requested changes
Had one small comment, besides that looks great

2023-06-13 01:35 UTC, Mustaballer commented on hackathon_site/dashboard/frontend/src/components/dashboard/ItemTable/ItemTable.tsx
> +    const [orderId, setorderId] = useState(0);
Can you replace the `0` with `null`, because setting it to 0 indicates it's given an id, which by default it should not be.

2023-06-13 01:36 UTC, Mustaballer commented on hackathon_site/dashboard/frontend/src/components/general/PopupModal/PopupModal.tsx
> +                    <Button id="submitButton" onClick={submitHandler} color="primary">
is there a reason why you have the Button a `submitButton` id?

2023-06-18 05:32 UTC, Mustaballer requested changes
Sorry one last thing, can you change the names of `submitModal` and `setModal`? I think its a bit too general since its being used for cancelling orders and should have a name about that. Thanks :)

2023-06-18 23:30 UTC, danielqiuu approved these changes

2023-06-18 23:42 UTC, Mustaballer approved these changes
Great work!

2023-06-18 23:42 UTC, Mustaballer commented
Please also create a PR in newhacks-site-2023 repo as well :)

2023-06-20 04:35 UTC, merged