Add popupmodal into TeamActionTable
ieeeuoft/hackathon-template pull request #505
Opened 2023-06-19 23:31 UTC by ishika1202

## Overview

- Resolves #<number>
- <Description of all changes made and features implemented>

## Unit Tests Created

- <Briefly describe unit tests that were created>

## Steps to QA

- <Steps for a reviewer to QA your work>

2023-07-22 14:31 UTC, lukecheseldine requested changes, later dismissed
hey Ishika, this is really good, you're almost there!

i noticed though that the delete doesn't work if the team has unreturned orders. i tried to delete the team below (with unreturned orders) and it failed. this is intentional design, but your feature doesn't handle the error well. see the screenshot below

![Screen Shot 2023-07-22 at 10 23 19 AM](https://github.com/ieeeuoft/hackathon-template/assets/36282235/4d917c9c-114e-4b1f-9225-264efd8707b6)

1. can we dispatch a more helpful snackbar message so the user knows why deletion failed? you can use the error message returned in the 400 response.
2. if this error occurs, can we stay on the team detail page of the team that they tried to delete? what happens now is: you're on the team detail page, you press delete, it doesn't delete and you are sent back to the team list page, where the snackbar is displayed. let's keep the user on the team detail page, so that they can easily resolve the unreturned orders and try to delete the team again if that's what they want to do.

please write a test case for the snackbar message too (don't need to test that they stay on the team detail page)

lmk if you need any help, great job! :D

2023-08-06 20:05 UTC, Mustaballer commented
@ishika1202 What's latest on this?

2023-12-27 01:58 UTC, Mustaballer approved these changes

2023-12-27 01:59 UTC, liu-samuel approved these changes

2023-12-27 02:05 UTC, merged